### ISSUE TITLE
Write first few exercises

### ISSUE THREAD

**Issue by samWson** [exercism/pharo#10]
We need a few exercises to get this language track started.

I haven't seen any activity in this repo for a few days. I thought I would get things moving by making some of the first few exercises, an also make sure I have the repo structure correct according to [this discussion](https://github.com/exercism/exercism-pharo-tooling/issues/4#issuecomment-402575116).

First pull request to follow soon. After that we can have some discussion to make sure the structure of the repo is on the right track.

#### Todo
- [x] HelloWorld exercise
- [x] TwoFer exercise

**Comment by samWson** [comment]
I've made a pull request for this at #11. Please read, review, and comment.

**Comment by bencoman** [comment]
To avoid confounding factors, I converted PR #11 to Tonel format in the 'master' branch of my own repo.
@samWson, @macta could you try it out in latest Pharo 7 like this...
![clone-pharo-exercism-tonel](https://user-images.githubusercontent.com/1713447/42694399-e1c8ce9a-86e4-11e8-8dd2-c41927cff679.png)

I'm not entirely satisfied with my structure, but I'd like your fresh view on it before adding my own.

Also I discovered that having the exercism repo called "pharo" conflicts with the default "pharo" repo definition built into Pharo 7.

**Comment by samWson** [comment]
@bencoman I'm using PharoLauncher on MacOS. I just downloaded a new image of Pharo 7 last night. I've copied and pasted the exercise code into the Pharo 7 image and made a new git repo. 

> Also I discovered that having the exercism repo called "pharo" conflicts with the default "pharo" repo definition built into Pharo 7.

I've managed to name the repo `pharo` without any problems so far. Although I create new git repositories by using the command line tool and then using Iceberg to add a local repository (I've had a miserable time getting Iceberg to make new repos). However I think it would be a good idea to make a better name to avoid potential conflicts.

I'll push the latest version of my work to the PR later tonight.

**Comment by macta** [comment]
Guys - I’d target Pharo 6, as 7 is going to be months (maybe even early next year) before it’s ready.

I’d hope we could have exercism launched next month with a few exercises?

If we do choose 7, the ide extension is a bit different (I actually wrote it first but then concluded 6.1 might be a better stable target)

**Comment by samWson** [comment]
The only barrier to using Pharo 6 is just getting started with Tonel in Iceberg as far as I can tell. From the Tonel [repository]() it looks simple enough to install Tonel, and as long as you have the `.properties` file specifying Tonel format Iceberg should use it correctly.

> I’d hope we could have exercism launched next month with a few exercises?

Totally agree. I think that time frame is manageable.

Have fun on holiday.

**Comment by bencoman** [comment]
> I've managed to name the repo pharo without any problems so far. 
Actually the clash I hit was forking the  "Exercism/Pharo"  repo on GitHub. I already had "pharo" It had to name my fork "pharo-1".

> I’d target Pharo 6, as 7 is going to be months (maybe even early next year) before it’s ready.
Okay. I just guessed Iceberg-Tonel were easier to use together with Pharo 7.  That only important to exercise devs anyhow.  The students can use Pharo 6.  And I guess for Pharo 6 our tool could have a dependency on Tonel to load its the latest stable into Pharo 6.

> If we do choose 7, the ide extension is a bit different (I actually wrote it first but then concluded 6.1 might be a better stable target)
Is any of the backend different, or just the GUI part?  Can I see the versions for both Pharo 6 & 7?

**Comment by macta** [comment]
@benconan it’s just a small bit of browser plugin code that differed. I’ll dig it out on Wed - although I recall it was pretty simple stuff.

**Comment by macta** [comment]
Guys - should we agree on a repo while we wait for the official exercism one ? (Mine was just an experiment short term - but had a good readme etc). Have to say I’m a bit frustrated we are stuck in limbo with little access or ability to try things out for real.

**Comment by macta** [comment]
@samwson I don’t think you need to update tonal in Pharo 6, it will use the newer format if we specify that .properties for new users. We also aren’t expecting them to use iceberg either - and my readme showed how to checkout everything from a simple cmd line.

**Comment by samWson** [comment]
> Have to say I’m a bit frustrated we are stuck in limbo with little access or ability to try things out for real.

@macta I've opened an issue [here](https://github.com/exercism/discussions/issues/220) to get some progress on this. The new version of Exercism has only just been deployed in the last few days so I presume a lot of people have been very busy. Hopefully we will get a response soon.

**Comment by macta** [comment]
I think we have this now - we need to focus on the core exercises (there is an issue already for this)
