### ISSUE TITLE
Testing macOS from scratch, Error: This URL was not recognised

### ISSUE THREAD

**Issue by samWson** [exercism/pharo#113]
With the new way of fetching and submitting via HTTP instead of `OSProcess`, I did a user test on macOS (Mojave 10.14) following our guide as a first time user might.

When trying to fetch `hello-world` I got the error 'This URL was not recognised'

The error was thrown in `ExercismDownload>>#getSolutionData`:
```smalltalk
getSolutionData
	| responseString response |
	httpclient 
		path: self path, '/latest';
		queryAt: 'track_id' put: track;
		queryAt: 'exercise_id' put: exercise.
		
	responseString := httpclient get.
	(httpclient response code = 401) ifTrue: [ (ExUnauthorized badToken: ApiToken) signal ].
	
	response := (STON fromString: responseString).
	response at: 'error' ifPresent: [ :error | self error: (error at: 'message') ]. "Error thrown here"
	solution := response at: 'solution'.
	ExercismManager solutionData at: exercise put: solution.
```

I inspected the `ExercismDownload` `httpclient` to see what the URL was:
```smalltalk
"a ZnClient"
self request uri "https://api.exercism.io:443/v1/solutions/latest/latest?track_id=pharo&exercise_id=hello-world"
```

A recent test on Windows 10 did not have this same problem. I'm not sure if the problem is with our tools or if the URL has been changed and we are using the wrong one.

**Comment by samWson** [comment]
@bencoman I used a completely fresh image. I see the same issue popped up on #31.

**Comment by bencoman** [comment]
Looking at the network chart... 
![exercism-merge](https://user-images.githubusercontent.com/1713447/48674044-28a5d580-eb83-11e8-9f04-5ea4445787a5.png)

the diff between master and its merge into apikey-better-error-handling left out some things, 
in particular line 74... https://github.com/exercism/pharo/compare/6bdb5b...0730023

So mainly we need to understand, what needs to be reinstated from 6bdb5b.

also btw, what was the merge process?  It would be useful to round out my general knowledge of things to watch out for.

**Comment by bencoman** [comment]
@samWson, @gregcline I think I've resolved it... https://github.com/exercism/pharo/network
 Could you try the updated "master" branch?

**Comment by samWson** [comment]
I've tired out the newest master on both macOS and Windows 10. It's working on both. I think we can call this issue fixed.
