### ISSUE TITLE
Close old branches

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo#114]
We currently have no open pull requests but 18 open branches, many already merged as seen at... https://github.com/exercism/pharo/network  and  https://github.com/exercism/pharo/branches
# Propose deleting the following branches... 
- ~~improved-installation-readme~~ - merged. remove.
- ~~environment-fixes~~ - merged. remove.
- ~~tools-code-cleanup~~ - merged. remove.
- ~~regenerate-base-examples~~ - merged. remove.
- ~~sum-of-multiples~~ - merged. remove.
- ~~acronym-exercises~~ - merged. remove.
- ~~issue-45~~ - merged. remove.
- ~~http-exercise-retrieval~~ - merged. remove.
- ~~improved-dev-readme~~ - merged. remove.
- ~~http-submit-exercises~~ - merged. remove.
- ~~apikey-better-error-handling~~ - merged. remove.
- ~~ExternalWebBrowser-support~~ branch list says merged although not reflected in the chart. I've verified all additions here are already in "master". Remove!

# Review of remaining...
- ~~fix-getting-started (Tim)~~ - looks merged in the network chart, but not-merged in repo list. @macta could you advise? 
- ~~intro-exercise-description-improvements & intro-exercise-description-improvements2 (Tim)~~ 
      Showing 12 changed files, 214 additions, 32 deletions. Too much for an unfamiliar quick review. 
      @macta could you advise. Seems related to closed issues #67 and #69. From the closing comment "Should have branched from master to exclude leap" I guess these branches should be thrown away??

# Review bencoman repo...
- ~~patch-1~~ (Ben) - verified this change is in "master". Remove!
- welcome-setup (Ben) - Tim didn't like this, but leave for the moment as a reference.
- ~~issue-10~~ (Samuel) - defines the TwoFer class - looks pre-Tonel and a different path.  @samWson please advise.
- ~~issue-10-tonel~~ (Ben) - defines the TwoFer class in Tonel format.  This is mine and I've no clue why its here.  Perhaps I was experimenting during the transition to Tonel.  Code already exists in "master".  Remove!
- risk-example - Demonstrates risk when user exercise sources mixed in with tool sources. Keep for now.

# Review jackhughesweb repo...
- auto-approve (Jack) - The impact of this is not clear. @jackhughesweb could you please advise?

**Comment by samWson** [comment]
I've deleted all those old branches except apikey-better-error-handling. I'm leaving that one alone until we fix #113 as it seems to be related.

**Comment by bencoman** [comment]
#113 fixed. I deleted apikey-better-error-handling

**Comment by macta** [comment]
I deleted mine too - they were old and nothing I recognise as important that can't be redone paricularly as the world has changed.
