### ISSUE TITLE
TonelWriter bug when generating exercises

### ISSUE THREAD

**Issue by samWson** [exercism/pharo#117]
I ran into this bug when trying to generate the exercise files (READMEs, source code etc.) for #83.

When running `ExercismGenerator class>>#generate` I get the following error: "Instance of RelativePath did not understand #pathString". 

The problem is in the method below with the `TonelWriter` instance. I remember I had the same problem when working on the `ExercismSubmit` solution [here](https://github.com/exercism/pharo/issues/96#issuecomment-433596078). In that issue the code was redundant and not needed but here we need to create files and a fix will be needed. 

I've noticed I can fix the error by adding the message send `#asFileReference` like so: `packageDir: (solutionDirectoryRef relativeTo: exampleDirectoryRef) asFileReference pathString;` but that still leaves the problem that `#sourceDir:` is not understood by `ExTonelWriter` or its super class. I'll carry on looking into this problem.

```smalltalk
ExercismGenerator>>#generateSourceFilesFor: packageOrTag to: filePathString
	"Generate the Tonel source files for a package (normally a tag). Answer the exercise directory reference"

	| writer exampleDirectoryRef exerciseDirectoryRef metaDirectoryRef  solutionDirectoryRef testClass testClassFilename exerciseName |
	
	"Note: could create the writer on a memory stream to then pick what should be stored on disk
	e.g.
		mem := FileSystem memory root.
		writer := ExTonelWriter on: mem."

	exerciseName := packageOrTag name asKebabCase.
	exampleDirectoryRef := filePathString asFileReference.
	exerciseDirectoryRef := exampleDirectoryRef / exerciseName.
	metaDirectoryRef :=  exerciseDirectoryRef / '.meta'.
	solutionDirectoryRef := metaDirectoryRef / 'solution'.
	
	exerciseDirectoryRef ensureCreateDirectory.
	exerciseDirectoryRef deleteAll.
	
	(writer := ExTonelWriter new)
                "Error: Instance of RelativePath did not understand #pathString"
		packageDir: (solutionDirectoryRef relativeTo: exampleDirectoryRef) pathString;
		sourceDir: exampleDirectoryRef;
		writeSnapshot: (self createTagSnapshotFor: packageOrTag).

	"Remove the extra package file as its not needed for Exercism"
	(solutionDirectoryRef / 'package.st') delete.
	
	self generateReadmeHintFor: packageOrTag to: metaDirectoryRef.
	
	"Move the test file down to the exerciseDirectory"
	testClass := packageOrTag classes detect: [ :cls | cls isTestCase  ].
	testClassFilename := testClass name, '.class.st'.
	(solutionDirectoryRef / testClassFilename) moveTo: exerciseDirectoryRef / testClassFilename.
	
	^exerciseDirectoryRef 
```

**Comment by bencoman** [comment]
It works in Pharo 7.  I've posted a question to pharo-dev mail list.

**Comment by samWson** [comment]
> It works in Pharo 7. I've posted a question to pharo-dev mail list.

That might be it. I've been forgetting to install the latest version of Iceberg each time I make a new image. Doing that installs the `MonticelloTonel-*` packages which might contain the missing methods. I'll try doing that next.

**Comment by samWson** [comment]
Quick update: I followed the instructions for updating Iceberg [here](https://github.com/pharo-vcs/iceberg#update-iceberg). That fixed the error "Instance of RelativePath did not understand #pathString", but I still have the problem where `#sourceDir:` is not understood by `ExTonelWriter`.

Is there a way to tell what version of packages are installed in an image i.e. compare the version of `MonticelloTonel-Core` I have installed in my image vs. what is available by default in Pharo7?

**Comment by bencoman** [comment]
I don't know. That would be a good question to the mail list.

**Comment by samWson** [comment]
I haven't been able to get any help on this from the mailing list or the Discord chat so I'm setting this aside. Now that Pharo7 is out I'm going to focus on seeing if our code will work there and if it will simplify some of our setup.

**Comment by macta** [comment]
I’m back from travels and can more actively chip in again although I’ve lost track if what is working or not . 

The original implementation worked in Pharo 7 (pre release), but I removed the Calypso pre-req in the hood we could launch in Pharo 6. We should target P7 now, so I guess I’ll load it up and see what happens.

It would be good to have a list of what’s needed to launch in P7 that we can work against.

**Comment by samWson** [comment]
@macta glad to have you back. It's been a couple of months for me but last I checked we had an almost working solution for the whole user cycle of download exercise to submit solution. I think the thing to do at the moment is to try out testing it like a user in Pharo7 and see what breaks. I'll draw up a new issue for this shortly.
