### ISSUE TITLE
Downloading an exercise is annoying as exercism is more geared to command line - we should parse the command line example on fetch

### ISSUE THREAD

**Issue by macta** [exercism/pharo#128]
The exercism site is really geared to command line junkies, and we don't have much control over the layout of the track site and the instructions that it gives.

Thus is shows an example for download like: `exercism download --exercise=acronym --track=pharo`

I propose we let you paste this into the fetch dialog (as well as `acronym`) and we can parse out the exercise and just fetch it.

This makes it much easier for users to crack on.

**Comment by bencoman** [comment]
This is cut-n-paste is exactly what I was trying to achieve from the Playground doing... 
```
ExercismDownload track: 'pharo' exercise: 'acronym'
```

**Comment by bencoman** [comment]
actually, one feature that impressed me when learning Pharo was controlling the GUI from the REPL.
For example we might do this...
```
Exercism download track: 'pharo' exercise: 'acronym' ; browse
```
where...
```
Exercism-class>>download
    ^ ExercismDownload new

ExercismDownload>>track: aStringTrack exercise: aStringExercise
	track := aStringTrack.
	exercise := aStringExercise asKebabCase.
	self execute

ExercismDownload>>browse
     "open system browser on the downloaded exercise"
```

**Comment by bencoman** [comment]
whoops, sorry. I think I missed your point, that the instructions are "standard" and presented only for their own client?

**Comment by macta** [comment]
@bencoman yes - my point was that we couldn't control the instructions on the exercism site (so nice - request on them).

For now - I've whacked in something that simply parses what their current site lets you easily copy to the clipboard - so now you can paste it into our fetch prompt (and not have to tediously edit it).

If we could control the instructions, it would be handy to have a way to easily copy the exercise kebab name AND as you suggest, easily copy what the playground command would be too (the latter I also like as it nicely shows that we do have a form of command line in the playground - but the former is also nice for just point and click too).

I guess I'll leave this issue open but rename.

**Comment by macta** [comment]
I'm closing this issue as we have a way to parse what we get from the existing template - but have opened up #132 which is what @bencoman spotted we should request.
