### ISSUE TITLE
Create ExercismGenerator

### ISSUE THREAD

**Issue by samWson** [exercism/pharo#14]
This tool will have the following responsibilities:
- [ ] Run all the tests of the reference solutions
- [ ] Generate Tonel files of the passing tests
- [ ] Place the Generated Tonel files in the `exercise` directory

The generated files are the tests cases that students will engineer solutions for. They are to be downloaded from Exercism.io and introduced into a Pharo image ready to run.

Ask any questions you need for information, or to clarify the scope of this tool.

**Comment by samWson** [comment]
@macta You probably have a better idea of what this needs to do, so please add anything you think is necessary for this issue.

**Comment by macta** [comment]
Yes - it was a placeholder. I’m back from holidays on thurs and can have a look at doing it. It’s not a huge amount of work.

**Comment by macta** [comment]
The basic generation is done - waiting on some testing and feedback.

Still Need to run all the the tests when generating (I have a spike ready for that).

Possibly Need something that checks config.json and flags if there is an example that isn’t in there (maybe configlet already does that - not sure?)

**Comment by samWson** [comment]
@macta I had a go at using the `ExercismGenerator` and this is what I found. 

For context, in my image (recently pulled from master) I have the two exercises in sub-packages of `Exercism`: `Exercsim-HelloWorld` and `Exercism-TwoFer`.

```smalltalk
ExercismGenerator class>>#generateTo: filePathString
	(RPackageOrganizer default packageNamed: 'Exercism') packages do: [:pkg |
			self generateFilesFor: pkg to: filePathString ]
 ```

The line `RPackageOrganizer default packageNamed: 'Exercism'` is only grabbing the `Exercism` package which is completely empty in my image. It does not get the two sub-packages containing the exercises. So nothing is being generated.

Tell me if there is something in my setup that is wrong.

Also I noticed this while browsing around `RPackageOrganizer`:
```smalltalk
RPackageOrganizer class>>#default
	"WARNING: Since this component can be changed (i.e. for testing) you should NOT use it directly. 
	  Use RPackage class>>#organizer instead"
	
	^ default ifNil: [  default := self new ]
```

Notice the comment in this method. It looks like `#default` can be considered unstable code. Later on you might want to change to the alternative suggested in the comment.

**Comment by macta** [comment]
Good spot - I’ll definitely swap from #default and see why my dev image was working (this is something we should plug into the CI build to act as a test - still small steps)

**Comment by macta** [comment]
@samWson I just tried it again, and I see a different behaviour, it writes out 3 examples hello-world, two-fer and reverse-string (i'm working on the last one) - however it incorrectly writes all 3 examples in each directory so they are all identical. I ran it by clicking on the green triangle on the ExercismGenerator generate method (it then shows me a directory prompter to choose where to generate).

This is after loading from master?

Are you not getting this? What OS?

**Comment by samWson** [comment]
I'm running macOS High Sierra 10.13.6 with Pharo version 6.1.

Have a look at the screen shot below. This is my image:
![exercism-packages](https://user-images.githubusercontent.com/13286932/43633000-fa1dae0c-975b-11e8-8520-6e972fc67e74.jpg)

After pulling from master and loading all the new packages the exercises don't seem to be grouped under the `Exercism` package as sub-packages. Notice how `ExercismDev` does group its sub-packages. I ran the code `RPackageOrganizer default packageNamed: 'ExercismDev'` in my playground, and the returned object contained all the sub-packages of `ExercismDev`. The same message send is used in the `ExercismGenerator class>>#generateTo:` with the argument `Exercism`.

I suspect that the `ExercismGenerator` is not running as expected because for some reason the exercise sub-packages are not getting nested under `Exercism` after pulling from master.

Pulling from master was a mess for me. I tend to use a combination of git at the command line and Iceberg so something may have gone wrong in the whole process. I may try a clean image and pull from master again, exclusively using Iceberg and see if there is any difference.

**Comment by macta** [comment]
@samwson try following the newer instructions I wrote up and you reviewed (the new readme.md). There is a proper baseline so it should load cleanly (it does in a clean OS X image when I do it).

**Comment by samWson** [comment]
@bencoman I ran that small experiment and I see what you mean. The top level package needs to be made first, then other sub-packages will naturally group under it.

@macta I used a clean image and loaded the repo by copying the code on the README directly into the playground. Everything loaded fine and the exercise sub-packages are properly grouped under the `Exercism` package. I ran the `generate` method by clicking on the green _play_ button. The exercise files were output in the directory I chose in tonel format.

I think we can call this as working now.

**Comment by macta** [comment]
Ah cool - maybe this is something we should highlight is the readme docs as I hadn’t realised how sensitive it was. Makes  a nice grouping in Pharo , but tags are a pain I’ve now learned.

Also heads up on an upcoming pr - the readme generation needs to better fit with how exercism intends with its templating.
