### ISSUE TITLE
Update the Pharo track intro text and provide a sample snippet

### ISSUE THREAD

**Issue by macta** [exercism/pharo#18]
When you first view the Pharo track, you are presented wit a concise summary of the language and why its important as well as simple code snippet.

We need to update the /docs/about.md and /docs/snippet.txt to wow people about Pharo and importance of Smalltalk

**Comment by kytrinyx** [comment]
Once the directory name is sorted out I can add Pharo back to to the website in beta mode.

**Comment by macta** [comment]
we’re waiting for @kytrinyx to come back from hols (Aug/1) to enable beta. Not sure if this will let us see the website page and logo in-situ to tweak it, but should let us try fetching examples from inside Pharo and submitting solutions and possibly seeing what mentor commenting is like?

**Comment by macta** [comment]
This is now unblocked, and the there is PR under review to tweak it.

**Comment by macta** [comment]
The initial docs are now in place and visible at https://exercism.io/my/tracks/pharo
