### ISSUE TITLE
TDD doesn't work so well with a missing class

### ISSUE THREAD

**Issue by macta** [exercism/pharo#60]
When we use TonelReader to load in code - missing classes are mapped to null - this means that TDD in the debugger isn't so hot - the debugger doesn't offer to create that class for you - you have to save the method in the debugger to cause it to spot the null class and offer to create it. You then can't press the create button for the missing method - you have to press proceed to get it to re-eval.

Its all a bit of a mess  - and something Pharo should be better at. 

Do we have to fix the debugger (might not be too hard)

**Comment by macta** [comment]
Some great feedback on the pharo list about this - there are some options we can try

**Comment by bencoman** [comment]
For the purpose of exercise, I think its reasonable for any class
referenced by the TestCase to be loaded as an empty stub.
Its not really giving the too much of a head start.  If they miss seeing
the magic of interactively auto-creating a class, oh well, there is
plenty of other magic to show them.   And if a solution needs a second
class, then they might be exposed to it then.
Any blocker to this?

**Comment by macta** [comment]
Well it’s more work - the Tonel writer outputs everything but we want a class with no methods - I evtkuve already written as an example with the name you want to use....

**Comment by macta** [comment]
@bencoman I couldn't resist fixing it (and using exercism as a trial for testing it works well).

I'll submit the changes back to pharo 7. It turns out it was a small amount of code (you just need the right code - the hardest bit was getting rid of a damn extra debugger window)

**Comment by bencoman** [comment]
On 12 August 2018 at 07:28, Tim Mackinnon <notifications@github.com> wrote:

> @bencoman <https://github.com/bencoman> I couldn't resist fixing it (and
> using exercism as a trial for testing it works well).
>
> I'll submit the changes back to pharo 7. It turns out it was a small
> amount of code (you just need the right code - the hardest bit was getting
> rid of a damn extra debugger window)
>

Side thought: If we are going to be introducing modifications into base
Pharo (which of course is fine and part of Pharo's attraction)
maybe later we even go further and add instructions to student and
"Exercism" labelling ??

cheers -ben

**Comment by macta** [comment]
Is this issue #19 - that’s kind of what I was thinking?

To keep it simple, We are a bit limited to what you can load or do on startup - but that’s quite a lot.

I guess we also need to get the versioning right too as we might need people to reload the changes and the package cache can cause issues. Will make an issue for that as it’s burned me when testing a few times.
