### ISSUE TITLE
Get approved logo to appear on site

### ISSUE THREAD

**Issue by macta** [exercism/pharo#65]
We have approval from the Pharo board to use the logo in /img (icon.png) - having checked it into our project it isn't appearing. 

@kytrinyx you seemed to infer that you can do something to get this aspect live? Is there anything we can do to make it so (are there any special size requirements or config we need to add)?

**Comment by macta** [comment]
I notice that @kytrinyx has put an issue onto exercism/website-logos(https://github.com/exercism/website-icons/issues/9) and there are a few others in there for a few weeks too.

**Comment by kytrinyx** [comment]
@macta Sorry this was unclear. We need Nicole to do the design for the logo to get it onto the site. We're all scrambling on all fronts to move things forward, so I don't know what her timeline is right now.

**Comment by bencoman** [comment]
> We need Nicole to do the design for the logo to get it onto the site. We're all scrambling on all fronts to move things forward, so I don't know what her timeline is right now.

@kytrinyx, Of course thats fine, but fyi I took one of the existing logos and replaced its center with our logo, then desaturated it to grey and colourized it with your theme color.
So maybe its right to go and only needs a quick review.
https://github.com/exercism/pharo/blob/ccf02659a88c8c32e0040fab4a82e1ea478adcce/img/icon.png

**Comment by kytrinyx** [comment]
I'm pretty sure Nicole has a process around it (we need several variations of the logo). I'll post a link to this for her in the open issue, though. Thanks!

**Comment by kytrinyx** [comment]
Oh. I already did! Nevermind.

**Comment by bencoman** [comment]
@kytrinyx I don't have a reference to Nicole's list.  Can we close our issue on this?

**Comment by kytrinyx** [comment]
Yeah, there are no further actions needed from you on this. 👍
