### ISSUE TITLE
Add installation guide for Windows users

### ISSUE THREAD

**Issue by samWson** [exercism/pharo#88]
Our current installation guide looks like it will work just fine on macOS and Linux, but Windows naturally doesn't have a Bash shell or curl. 

The simplest thing to do might be just the traditional Windows convention of _download from the website and install yourself_, then the usual double click on the icon. Copy, paste, and evaluate the code in the playground for Metacello to get the repo from git.

Probably a lot simpler than asking beginners to install a shell or the Windows Subsystem for Linux.

**Comment by macta** [comment]
Doesn’t recent windows come with a Linux like shell now? I thought they added it because web development is so command line based now.

I’m curious how exercism itself runs on Windows as that is all command line too.

We can of course add more gui based instructions - but might be worth double-checking.

A few weeks ago, didn’t someone ping us to help - and were they a windows user?

**Comment by samWson** [comment]
> Doesn’t recent windows come with a Linux like shell now?

That's the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) or WSL. It only works for Windows 10, so for anyone on Windows 7 or 8 it's a no-go. 

It's not hard to get up and running, but I just coached some beginner programmers recently and I am reminded that what's basic for even junior programmers is incomprehensible for beginners. The target market for the WSL is developers however, which is probably what most of Exercisms students are or aspire to be. 

I just had a quick read of installing the Exercism CLI on Windows and it doesn't look like it uses the WSL, so it is probably a native solution. I don't how well the WSL can interact with a native CLI. I'll give this a try over the next few days.

> A few weeks ago, didn’t someone ping us to help - and were they a windows user?

I was thinking of asking that person if they wanted to start. It's looks like we are ready for some beta testing or at least very close. What do you think?

**Comment by macta** [comment]
If you can help run with this one - it seems like a great addition.

For now, perhaps add a note to the current install doc that for Windows should use a
Manual install and docs are sop for them?

**Comment by samWson** [comment]
I just installed the exercism CLI on my Windows 10 machine using the windows installer. I can use the CLI through CMD, powershell, and the WSL bash without any further configuration. You have to use `exercism.exe` instead of `exercism` but it works.

Unfortunately when I run `curl https://get.pharo.org | bash` I get the error `Failed to connect to get.pharo.org port 443: Connection refused`. I also tried `telnet localhost 443` to see if it wasn't just curl and that has a similar error. This is all on the WSL bash. My AV firewall doesn't seem to be the problem as I get the same errors with the shields down.

Until we can figure that out I'll start work on a Windows installation guide. It won't be much work since after installation the same commands can be evaluated in the playground. I'll also get in touch with @gregcline and see if they are still interested in beta testing the Windows experience.

**Comment by samWson** [comment]
Merged, but I suspect there will be more tweaking of these instructions to come as we do more user testing.
