### ISSUE TITLE
Syntax highlighting for pharo

### ISSUE THREAD

**Issue by jackhughesweb** [exercism/pharo#9]
This track has not yet specified the file format mapping 
for syntax highlighting in exercism/meta#90

Please provide a mapping of file formats used by your track
in exercism/meta#90 (e.g. md = markdown)

This issue can be closed after this is completed. (Apologies
if you've already done this - this issue was generated
automatically).

**Comment by bencoman** [comment]
To exercism/meta#90 I added...
    .st = Smalltalk
This is the traditional extension, and Pharo has continued to use it for the new Tonel format.
e.g. https://github.com/pharo-project/pharo/blob/development/src/Balloon/BalloonEdgeData.class.st
I guess that is all that is needed.
