### ISSUE TITLE
Better error handling for mis-entering api key 

### ISSUE THREAD

**Issue by macta** [exercism/pharo#94]
If you enter an incorrect key we don’t handle the error and let you retry. Needs better error handling instead of just throwing an error as reported by @gregcline

**Comment by gregcline** [comment]
1. Download Exercism Manager
2. Run `ExercismManager welcome.`
3. Right click and select `Fetch Exercise...`
4. Enter invalid token when prompted for an API token (I put hello-world)
5. Enter exercise name (hello-world)

Results in `KeyNotFound: key 'solution' not found in Dictionary`

**Comment by bencoman** [comment]
@gregcline Would you be interested in having another go?

**Comment by gregcline** [comment]
Yeah I'm actually in the midst right now.

**Comment by samWson** [comment]
Looks like this issue is fixed. Closing.
